# Скачиваем библиотеки ***"pandas"*** (библиотека для обработки и анализа данных) и ***"openpyxl"*** (библиотека для чтения/записи файлов Excel с расширениями xlsx/xlsm/xltx/xltm).
---

In [ ]:
!pip install pandas openpyxl
import pandas as pd

## Снимаем ограничение на количество отображаемых колонок.
---

In [2]:
pd.set_option("display.max_columns", None)

## **1**. Посмотреть данные через `head`, `tail`, `describe`, `info` до внесения изменений.
---

In [3]:
# Загрузка Excel-файла в объект DataFrame.
# Метод pd.read_excel считывает данные из файла Excel (формата .xlsx, .xls) и загружает в таблицу.
df_excel = pd.read_excel("korzinka_deliveries.xlsx", engine = "openpyxl")

# Отображаем первые 5 строк датафрейма
df_excel.head()

,Номер \nзаказа,Филиал,Платформа,Оценка заказа,Статус,Дата \nсоздания \nзаказа,Время \nсоздания \nзаказа,Время \nприема \nзаказа,Тип доставки,Указаное \nдата \nдоставки,Указаное \nвремя \nдоставки,Фактическое \nвремя \nдоставки,Опоздание,Статус \nоплаты,Метод \nоплаты,Тип карты,"Стоимость товаров\nпосле формирование, сумы","Сумма \nпо чеку, сумы","Минимальная \nсумма \nдоставки, сумы",Оплата через\nсистему\nStripe ($),Оплата через\nсистему\nOcto (sum),Всего\nоплачено\nс картой,Время \nзагрузки чека,Id Сборщика,ID Доставщика,Номер \nклиента,Район \nдоставки,Номер \nадреса доставки
0,471057,Юнусобод,iOS,0,Доставлено,26-12-2020,18:51,08:45,По расписанию,30-01-2021,16:00,15:14,-45.0,Оплачен,Онлайн карта,Visa,584364,584064.00,15000,0.0,624020.0,624020.0,30-01-2021 15:14,1.0,1.0,48429363056,Шайхантахурский район,3.995964e+12
1,472573,Сергели,Win32,0,Доставлено,29-12-2020,15:13,08:14,По расписанию,04-01-2021,11:00,10:15,-44.0,Оплачен,Наличными,NaN,170671,170671.00,15000,0.0,0.0,0.0,04-01-2021 10:01,2.0,2.0,2996136003341,Сергелийский район,3.994850e+12
2,473587,Файзабад,Android,5,Доставлено,30-12-2020,22:42,08:46,По расписанию,03-01-2021,12:00,10:40,-79.0,Оплачен,Онлайн карта + Баллы,Visa,354339,365439.14,15000,0.0,350431.0,350431.0,03-01-2021 09:38,3.0,3.0,40424143817,Яшнабадский район,3.995917e+12
3,473792,Сергели,iOS,5,Доставлено,31-12-2020,11:29,08:11,По расписанию,05-01-2021,14:00,13:19,-40.0,Оплачен,Онлайн карта,Visa,598142,597542.00,15000,0.0,635596.0,635596.0,05-01-2021 12:46,4.0,2.0,57756661892,Сергелийский район,7.700888e+10
4,473798,Shedevr,Android,0,Доставлено,31-12-2020,11:44,09:59,По расписанию,02-01-2021,15:00,12:21,-158.0,Оплачен,Онлайн карта,Uzcard,143680,143680.70,15000,0.0,0.0,146020.0,02-01-2021 11:46,5.0,3.0,2996727962468,Юнусабадский район,3.995637e+12

In [4]:
# Отображаем последние 5 строк датафрейма
df_excel.tail()

,Номер \nзаказа,Филиал,Платформа,Оценка заказа,Статус,Дата \nсоздания \nзаказа,Время \nсоздания \nзаказа,Время \nприема \nзаказа,Тип доставки,Указаное \nдата \nдоставки,Указаное \nвремя \nдоставки,Фактическое \nвремя \nдоставки,Опоздание,Статус \nоплаты,Метод \nоплаты,Тип карты,"Стоимость товаров\nпосле формирование, сумы","Сумма \nпо чеку, сумы","Минимальная \nсумма \nдоставки, сумы",Оплата через\nсистему\nStripe ($),Оплата через\nсистему\nOcto (sum),Всего\nоплачено\nс картой,Время \nзагрузки чека,Id Сборщика,ID Доставщика,Номер \nклиента,Район \nдоставки,Номер \nадреса доставки
133427,638467,Салом,Android,5,Доставлено,31-12-2021,12:24,12:37,По расписанию,31-12-2021,15:00,15:15,15.0,Оплачен,Онлайн карта,Uzcard,511673,511328.44,15000,0.0,0.0,511328.0,31-12-2021 14:47,36.0,131.0,2996914684805,Мирзо-Улугбекский район,3.995886e+12
133428,638468,Беруний,iOS,0,Доставлено,31-12-2021,12:32,12:36,По расписанию,31-12-2021,15:00,14:24,-35.0,Оплачен,Онлайн карта,Uzcard,235658,231948.70,15000,0.0,0.0,231948.0,31-12-2021 13:31,4.0,119.0,2996727072362,Алмазарский район,3.995636e+12
133429,638469,Салом,Linux aarch64,0,Доставлено,31-12-2021,12:33,12:43,По расписанию,31-12-2021,15:00,14:40,-19.0,Оплачен,Онлайн карта,Visa,343008,369498.60,15000,0.0,408449.8,408449.8,31-12-2021 14:29,92.0,191.0,2996839073492,Яшнабадский район,3.995785e+12
133430,638470,Салом,iOS,3,Доставлено,31-12-2021,12:44,12:52,По расписанию,31-12-2021,15:00,15:27,27.0,Оплачен,Наличными,NaN,314454,314454.04,15000,0.0,0.0,0.0,31-12-2021 14:51,36.0,125.0,2996914396715,Мирзо-Улугбекский район,3.995886e+12
133431,638473,Салом,iOS,0,Доставлено,31-12-2021,12:49,13:04,По расписанию,31-12-2021,15:00,15:09,9.0,Оплачен,Наличными,NaN,274241,274751.84,15000,0.0,0.0,0.0,31-12-2021 14:46,51.0,131.0,2996711102192,Мирзо-Улугбекский район,3.995615e+12

In [5]:
# Метод describe() используется для получения сводной статистики по DataFrame.
# Он автоматически рассчитывает количество ненулевых значений (count), среднее значение (mean),
# стандартное отклонение (std / разброс данных), минимальное значение (min), 25-й, 50-й (медиана) и 75-й процентили (quartiles), а также максимальное значение (max)
# для каждого числового столбца в DataFrame df_excel.
df_excel.describe()

,Номер \nзаказа,Оценка заказа,Опоздание,"Стоимость товаров\nпосле формирование, сумы","Сумма \nпо чеку, сумы","Минимальная \nсумма \nдоставки, сумы",Оплата через\nсистему\nStripe ($),Оплата через\nсистему\nOcto (sum),Всего\nоплачено\nс картой,Id Сборщика,ID Доставщика,Номер \nклиента,Номер \nадреса доставки
count,133432.000000,133432.000000,133371.000000,1.334320e+05,1.334320e+05,133432.000000,133432.000000,1.334320e+05,1.334320e+05,132433.00000,133423.000000,1.334320e+05,1.324290e+05
mean,554947.482493,1.035479,-17.611715,3.138700e+05,3.126524e+05,14873.793393,0.014913,6.556238e+04,1.806843e+05,37.14066,76.667389,2.835391e+12,1.602103e+21
std,47199.636471,1.970045,363.415501,3.309387e+05,3.209582e+05,5196.972807,1.536663,3.063868e+05,3.520568e+05,23.19610,63.825378,7.309296e+11,7.992465e+22
min,471057.000000,0.000000,-8664.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,1.00000,1.000000,1.423980e+10,3.992423e+06
25%,514449.750000,0.000000,-44.000000,1.334198e+05,1.329208e+05,15000.000000,0.000000,0.000000e+00,0.000000e+00,18.00000,11.000000,2.996711e+12,3.995615e+12
50%,554508.500000,0.000000,-22.000000,2.273240e+05,2.265533e+05,15000.000000,0.000000,0.000000e+00,0.000000e+00,37.00000,60.000000,2.996730e+12,3.995645e+12
75%,594762.500000,0.000000,-5.000000,3.807160e+05,3.795951e+05,15000.000000,0.000000,0.000000e+00,2.487505e+05,55.00000,134.000000,2.996923e+12,3.995897e+12
max,638473.000000,5.000000,61684.000000,2.818497e+07,1.192000e+07,30000.000000,314.770000,1.516613e+07,1.516613e+07,98.00000,193.000000,2.933940e+13,3.995885e+24

In [6]:
# Функция info() показывает информацию о DataFrame
# Включая типы данных и использование памяти
# memory_usage = "deep" позволяет получить более точную информацию о потреблении памяти
# Важно отметить, что использование memory_usage = "deep" может занять больше времени, так как оно требует дополнительного анализа
df_excel.info(memory_usage = "deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133432 entries, 0 to 133431
Data columns (total 28 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   Номер
заказа                               133432 non-null  int64
 1   Филиал                                      133432 non-null  object
 2   Платформа                                   133432 non-null  object
 3   Оценка заказа                               133432 non-null  int64
 4   Статус                                      133432 non-null  object
 5   Дата
создания
заказа                      133432 non-null  object
 6   Время
создания
заказа                     133432 non-null  object
 7   Время
приема
заказа                       133403 non-null  object
 8   Тип доставки                                133426 non-null  object
 9   Указаное
дата
доставки                    133432 non-null  object
 10  Указаное
время
доставки                   133432 non-null  object
 11  Фактическое
время
доставки                133371 non-null  object
 12  Опоздание                                   133371 non-null  float64
 13  Статус
оплаты                              133432 non-null  object
 14  Метод
оплаты                               133432 non-null  object
 15  Тип карты                                   62078 non-null   object
 16  Стоимость товаров
после формирование, сумы  133432 non-null  int64
 17  Сумма
по чеку, сумы                        133432 non-null  float64
 18  Минимальная
сумма
доставки, сумы          133432 non-null  int64
 19  Оплата через
систему
Stripe ($)             133432 non-null  float64
 20  Оплата через
систему
Octo (sum)             133432 non-null  float64
 21  Всего
оплачено
с картой                     133432 non-null  float64
 22  Время
загрузки чека                        129597 non-null  object
 23  Id Сборщика                                 132433 non-null  float64
 24  ID Доставщика                               133423 non-null  float64
 25  Номер
клиента                              133432 non-null  int64
 26  Район
доставки                             126868 non-null  object
 27  Номер
адреса доставки                      132429 non-null  float64
dtypes: float64(8), int64(5), object(15)
memory usage: 142.4 MB

## **2**. Переименовать колонки и убрать символ переноса строки \n из названий, например: "Номер \nзаказа" -> "Номер заказов".
---
### Были обнаружены орфографические и смысловые ошибки в названиях столбцов:

| Оригинал | Рекомендованное исправление | Ожидаемый результат |
| ----------- | ----------- | ----------- |
| Номер заказа | Номер заказов | Номер заказов |
| Указаное дата доставки | Указанная дата доставки | ❌ Ошибка: указаное → указанная |
| Указаное время доставки | Указанное время доставки | ❌ Ошибка: указаное → указанное |
| Стоимость товаров после формирование, сумы | Стоимость товаров после формирования, сум | ❌ формирование → формирования, и сумы → сум |
| Сумма по чеку, сумы | Сумма по чеку, сум | ❌ сумы → сум |
| Минимальная сумма доставки, сумы | Минимальная сумма доставки, сум | ❌ сумы → сум |
| Оплата через систему Octo (sum) | Оплата через систему Octo (сум) | ❌ sum → сум (русский язык) |
| Всего оплачено с картой | Всего оплачено с карты | ✔ Логичнее: оплачено с карты, а не с картой |
| Id Сборщика | ID Сборщика | ⚠️ Id → ID (принято писать в верхнем регистре) |
---

In [7]:
# Импортируем модуль регулярных выражений для работы с шаблонами замены
import re

# Шаг 1: Очистка от \n и лишних пробелов
# .rename() — метод, который позволяет переименовать столбцы и индексы в DataFrame
# columns = ... — указывает, что мы хотим переименовать столбцы
# lambda x: ... — это анонимная функция, применяемая к каждому названию столбца
# re.sub(r"\s+", " ", x) — заменяет все подряд идущие пробельные символы (включая пробелы, \n, табуляции) на один пробел
# .sub() — функция из модуля re, которая заменяет все вхождения шаблона на заданную строку
# r"\s+" - буква r перед строкой указывает на то, что это "сырая" строка, в которой обратные слеши не экранируются
# \s — соответствует любому пробельному символу (пробел, табуляция, перенос строки и т.д.)
# + — означает "один или более" (то есть, если пробельных символов несколько подряд, они будут заменены на один пробел)
# .strip() — удаляет пробелы в начале и в конце строки
# inplace=True — означает, что изменения будут внесены непосредственно в исходный DataFrame df_excel
# Результат — чистые и единообразные названия столбцов без лишних пробелов и переносов
df_excel.rename(columns = lambda x: re.sub(r"\s+", " ", x).strip(), inplace = True)

# Шаг 2: Переименование столбцов на корректные имена
corrected_columns = {
    "Номер заказа": "Номер заказов",
    "Указаное дата доставки": "Указанная дата доставки",
    "Указаное время доставки": "Указанное время доставки",
    "Стоимость товаров после формирование, сумы": "Стоимость товаров после формирования, сум",
    "Сумма по чеку, сумы": "Сумма по чеку, сум",
    "Минимальная сумма доставки, сумы": "Минимальная сумма доставки, сум",
    "Оплата через систему Octo (sum)": "Оплата через систему Octo (сум)",
    "Всего оплачено с картой": "Всего оплачено с карты",
    "Id Сборщика": "ID Сборщика"
}

df_excel.rename(columns = corrected_columns, inplace = True)

# Показываем имена столбцов
df_excel.columns

Index(['Номер заказов', 'Филиал', 'Платформа', 'Оценка заказа', 'Статус',
       'Дата создания заказа', 'Время создания заказа', 'Время приема заказа',
       'Тип доставки', 'Указанная дата доставки', 'Указанное время доставки',
       'Фактическое время доставки', 'Опоздание', 'Статус оплаты',
       'Метод оплаты', 'Тип карты',
       'Стоимость товаров после формирования, сум', 'Сумма по чеку, сум',
       'Минимальная сумма доставки, сум', 'Оплата через систему Stripe ($)',
       'Оплата через систему Octo (сум)', 'Всего оплачено с карты',
       'Время загрузки чека', 'ID Сборщика', 'ID Доставщика', 'Номер клиента',
       'Район доставки', 'Номер адреса доставки'],
      dtype='object')

## **3**. Все ID привести к формату int (например, заменить 1.0 на 1).
---

In [8]:
# Проходим по всем названиям столбцов в таблице df_excel
for col in df_excel.columns:
    # Проверяем, содержит ли название столбца подстроку "ID"
    # Это позволяет выбрать все столбцы, которые являются идентификаторами
    if "ID" in col:
        # Преобразуем тип данных в Int64 (nullable integer):
        # - позволяет работать с целыми числами
        # - сохраняет пропущенные значения (NaN)
        # - устраняет дробную часть у чисел вроде 1.0 → 1
        df_excel[col] = df_excel[col].astype("Int64")

# Проверяем, что все столбцы с ID имеют тип Int64
df_excel[["ID Доставщика", "ID Сборщика"]].dtypes

ID Доставщика    Int64
ID Сборщика      Int64
dtype: object

## **4**. Поменять отображение последней колонки (например, **"Номер адреса доставки"**), чтобы числа не отображались в формате scientific notation (e+12), а были обычными целыми числами.
---

In [9]:
# Получаем название последнего столбца в датафрейме ("Номер адреса доставки")
last_col = df_excel.columns[-1]

# Преобразование последней колонки в целые числа БЕЗ научной нотации:
# .fillna(0) — заменяет NaN на 0
# .round(0) — если есть float с дробной частью, делает округление
# .astype(int) — приводит к int (бросит ошибку, если остаются нецелые значения)
df_excel[last_col] = df_excel[last_col].fillna(0).round(0).astype(int)

# Проверяем результат преобразования: первые 10 строк датафрейма последней строки "Номер адреса доставки"
df_excel[[last_col]].head(10)

   Номер адреса доставки
0          3995964031191
1          3994850040891
2          3995916514455
3            77008882519
4          3995637283287
5          3995614824203
6          3995993089131
7          3995910071083
8           319215673227
9           187052751115

## **5**. Перевести все колонки с типом данных времени на формат `"datetime"`.
---
### Результат анализа всех потенциальных колонок с типом данных "время" по фактическому содержимому:
| Название колонки | Ожидаемый результат |
| ----------- | ----------- |
| Дата создания заказа | ✅ Содержит дату. Преобразовать к `datetime`. |
| Указанная дата доставки | ✅ Содержит дату. Преобразовать к `datetime`. |
| Время создания заказа | ✅ Содержит только время. Преобразовать в `datetime`. |
| Время приема заказа | ✅ Содержит только время. Преобразовать в `datetime`.|
| Указанное время доставки | ✅ Содержит только время. Преобразовать в `datetime`. |
| Фактическое время доставки | ✅ Содержит только время. Преобразовать в `datetime`. |
| Время загрузки чека | ✅ Преобразовать к `datetime` с форматом %d-%m-%Y %H:%M. |

### ⚠️ При приведении столбцов с временем (например: **"12:45"**) к формату datetime, pandas автоматически добавляет дату по умолчанию (**1900-01-01**), так как тип данных datetime64[ns] требует наличия и даты, и времени.

### Удалить эту дату, оставив при этом тип `datetime64`, невозможно — в этом случае придётся использовать тип datetime.time, который в pandas хранится как `object`, что противоречит требованию "преобразовать в `datetime`".

### Поэтому оставляем тип `datetime64[ns]` для дальнейшего анализа, а для корректного визуального отображения времени — используем метод `.dt.time`.

### Финальная очистка отображения возможна при экспорте в **Excel** (например, через форматирование колонок).
---

In [10]:
# 1. Указываем группы столбцов по содержанию
# Колонки, содержащие только ДАТУ в формате "dd-mm-YYYY"
date_only_columns = [
    "Дата создания заказа",
    "Указанная дата доставки"
]

# Колонки, содержащие только ВРЕМЯ в формате "HH:MM"
# Преобразовать в datetime, где дата будет по дэфолту в формате(1900-01-01)
time_only_columns = [
    "Время создания заказа",
    "Время приема заказа",
    "Указанное время доставки",
    "Фактическое время доставки"
]

# Колонка с датой и временем — формат: "dd-mm-YYYY HH:MM"
datetime_columns = [
    "Время загрузки чека"
]

# 2. Преобразуем столбцы с датами
# Используем формат "%d-%m-%Y" — день-месяц-год
# Указываем dayfirst=True, чтобы Pandas правильно понял день и месяц
for col in date_only_columns:
    df_excel[col] = pd.to_datetime(
        df_excel[col],
        format = "%d-%m-%Y",  # Пример: "31-12-2021"
        errors = "coerce",    # если значение не удаётся преобразовать, то → NaT
        dayfirst = True       # указываем, что сначала идёт день (а не месяц)
    )

# 3. Преобразуем столбцы с временем
# Используем формат "%H:%M" — часы и минуты (например, 12:45)
# Дата при этом будет по умолчанию в формате — 1900-01-01
for col in time_only_columns:
    df_excel[col] = pd.to_datetime(
        df_excel[col],
        format = "%H:%M",    # Пример: "12-45" → 1900-01-01 12:45:00
        errors = "coerce"    # если значение не удаётся преобразовать, то → NaT
    ).dt.time  # оставляем только время (без даты)

# 4. Преобразуем столбцы с датой и временем
# Используем формат "%d-%m-%Y %H:%M"
# Например: "31-12-2021 14:45"
for col in datetime_columns:
    df_excel[col] = pd.to_datetime(
        df_excel[col],
        format = "%d-%m-%Y %H:%M",  # Пример: "31-12-2021 14:30"
        errors = "coerce",          # если значение не удаётся преобразовать, то → NaT
        dayfirst = True             # указываем, что сначала идёт день (а не месяц)
    )

# 5. Проверяем результат преобразования: первые 5 строк датафрейма
df_excel[date_only_columns + time_only_columns + datetime_columns].head()

,Дата создания заказа,Указанная дата доставки,Время создания заказа,Время приема заказа,Указанное время доставки,Фактическое время доставки,Время загрузки чека
0,2020-12-26,2021-01-30,18:51:00,08:45:00,16:00:00,15:14:00,2021-01-30 15:14:00
1,2020-12-29,2021-01-04,15:13:00,08:14:00,11:00:00,10:15:00,2021-01-04 10:01:00
2,2020-12-30,2021-01-03,22:42:00,08:46:00,12:00:00,10:40:00,2021-01-03 09:38:00
3,2020-12-31,2021-01-05,11:29:00,08:11:00,14:00:00,13:19:00,2021-01-05 12:46:00
4,2020-12-31,2021-01-02,11:44:00,09:59:00,15:00:00,12:21:00,2021-01-02 11:46:00

## **6**. Ещё раз посмотреть данные с помощью `head`, `tail`, `info`, `describe`, чтобы сравнить изменения с шагом 1
---

In [11]:
df_excel.head()

,Номер заказов,Филиал,Платформа,Оценка заказа,Статус,Дата создания заказа,Время создания заказа,Время приема заказа,Тип доставки,Указанная дата доставки,Указанное время доставки,Фактическое время доставки,Опоздание,Статус оплаты,Метод оплаты,Тип карты,"Стоимость товаров после формирования, сум","Сумма по чеку, сум","Минимальная сумма доставки, сум",Оплата через систему Stripe ($),Оплата через систему Octo (сум),Всего оплачено с карты,Время загрузки чека,ID Сборщика,ID Доставщика,Номер клиента,Район доставки,Номер адреса доставки
0,471057,Юнусобод,iOS,0,Доставлено,2020-12-26,18:51:00,08:45:00,По расписанию,2021-01-30,16:00:00,15:14:00,-45.0,Оплачен,Онлайн карта,Visa,584364,584064.00,15000,0.0,624020.0,624020.0,2021-01-30 15:14:00,1,1,48429363056,Шайхантахурский район,3995964031191
1,472573,Сергели,Win32,0,Доставлено,2020-12-29,15:13:00,08:14:00,По расписанию,2021-01-04,11:00:00,10:15:00,-44.0,Оплачен,Наличными,NaN,170671,170671.00,15000,0.0,0.0,0.0,2021-01-04 10:01:00,2,2,2996136003341,Сергелийский район,3994850040891
2,473587,Файзабад,Android,5,Доставлено,2020-12-30,22:42:00,08:46:00,По расписанию,2021-01-03,12:00:00,10:40:00,-79.0,Оплачен,Онлайн карта + Баллы,Visa,354339,365439.14,15000,0.0,350431.0,350431.0,2021-01-03 09:38:00,3,3,40424143817,Яшнабадский район,3995916514455
3,473792,Сергели,iOS,5,Доставлено,2020-12-31,11:29:00,08:11:00,По расписанию,2021-01-05,14:00:00,13:19:00,-40.0,Оплачен,Онлайн карта,Visa,598142,597542.00,15000,0.0,635596.0,635596.0,2021-01-05 12:46:00,4,2,57756661892,Сергелийский район,77008882519
4,473798,Shedevr,Android,0,Доставлено,2020-12-31,11:44:00,09:59:00,По расписанию,2021-01-02,15:00:00,12:21:00,-158.0,Оплачен,Онлайн карта,Uzcard,143680,143680.70,15000,0.0,0.0,146020.0,2021-01-02 11:46:00,5,3,2996727962468,Юнусабадский район,3995637283287

In [12]:
df_excel.tail()

,Номер заказов,Филиал,Платформа,Оценка заказа,Статус,Дата создания заказа,Время создания заказа,Время приема заказа,Тип доставки,Указанная дата доставки,Указанное время доставки,Фактическое время доставки,Опоздание,Статус оплаты,Метод оплаты,Тип карты,"Стоимость товаров после формирования, сум","Сумма по чеку, сум","Минимальная сумма доставки, сум",Оплата через систему Stripe ($),Оплата через систему Octo (сум),Всего оплачено с карты,Время загрузки чека,ID Сборщика,ID Доставщика,Номер клиента,Район доставки,Номер адреса доставки
133427,638467,Салом,Android,5,Доставлено,2021-12-31,12:24:00,12:37:00,По расписанию,2021-12-31,15:00:00,15:15:00,15.0,Оплачен,Онлайн карта,Uzcard,511673,511328.44,15000,0.0,0.0,511328.0,2021-12-31 14:47:00,36,131,2996914684805,Мирзо-Улугбекский район,3995886246403
133428,638468,Беруний,iOS,0,Доставлено,2021-12-31,12:32:00,12:36:00,По расписанию,2021-12-31,15:00:00,14:24:00,-35.0,Оплачен,Онлайн карта,Uzcard,235658,231948.70,15000,0.0,0.0,231948.0,2021-12-31 13:31:00,4,119,2996727072362,Алмазарский район,3995636096479
133429,638469,Салом,Linux aarch64,0,Доставлено,2021-12-31,12:33:00,12:43:00,По расписанию,2021-12-31,15:00:00,14:40:00,-19.0,Оплачен,Онлайн карта,Visa,343008,369498.60,15000,0.0,408449.8,408449.8,2021-12-31 14:29:00,92,191,2996839073492,Яшнабадский район,3995785431319
133430,638470,Салом,iOS,3,Доставлено,2021-12-31,12:44:00,12:52:00,По расписанию,2021-12-31,15:00:00,15:27:00,27.0,Оплачен,Наличными,NaN,314454,314454.04,15000,0.0,0.0,0.0,2021-12-31 14:51:00,36,125,2996914396715,Мирзо-Улугбекский район,3995885862283
133431,638473,Салом,iOS,0,Доставлено,2021-12-31,12:49:00,13:04:00,По расписанию,2021-12-31,15:00:00,15:09:00,9.0,Оплачен,Наличными,NaN,274241,274751.84,15000,0.0,0.0,0.0,2021-12-31 14:46:00,51,131,2996711102192,Мирзо-Улугбекский район,3995614802919

In [13]:
df_excel.info(memory_usage = "deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133432 entries, 0 to 133431
Data columns (total 28 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Номер заказов                              133432 non-null  int64
 1   Филиал                                     133432 non-null  object
 2   Платформа                                  133432 non-null  object
 3   Оценка заказа                              133432 non-null  int64
 4   Статус                                     133432 non-null  object
 5   Дата создания заказа                       133432 non-null  datetime64[ns]
 6   Время создания заказа                      133432 non-null  object
 7   Время приема заказа                        133403 non-null  object
 8   Тип доставки                               133426 non-null  object
 9   Указанная дата доставки                    133432 non-null  datetime64[ns]
 10  Указанное время доставки                   133432 non-null  object
 11  Фактическое время доставки                 133371 non-null  object
 12  Опоздание                                  133371 non-null  float64
 13  Статус оплаты                              133432 non-null  object
 14  Метод оплаты                               133432 non-null  object
 15  Тип карты                                  62078 non-null   object
 16  Стоимость товаров после формирования, сум  133432 non-null  int64
 17  Сумма по чеку, сум                         133432 non-null  float64
 18  Минимальная сумма доставки, сум            133432 non-null  int64
 19  Оплата через систему Stripe ($)            133432 non-null  float64
 20  Оплата через систему Octo (сум)            133432 non-null  float64
 21  Всего оплачено с карты                     133432 non-null  float64
 22  Время загрузки чека                        129597 non-null  datetime64[ns]
 23  ID Сборщика                                132433 non-null  Int64
 24  ID Доставщика                              133423 non-null  Int64
 25  Номер клиента                              133432 non-null  int64
 26  Район доставки                             126868 non-null  object
 27  Номер адреса доставки                      133432 non-null  int64
dtypes: Int64(2), datetime64[ns](3), float64(5), int64(6), object(12)
memory usage: 119.5 MB

In [14]:
df_excel.describe()

,Номер заказов,Оценка заказа,Дата создания заказа,Указанная дата доставки,Опоздание,"Стоимость товаров после формирования, сум","Сумма по чеку, сум","Минимальная сумма доставки, сум",Оплата через систему Stripe ($),Оплата через систему Octo (сум),Всего оплачено с карты,Время загрузки чека,ID Сборщика,ID Доставщика,Номер клиента,Номер адреса доставки
count,133432.000000,133432.000000,133432,133432,133371.000000,1.334320e+05,1.334320e+05,133432.000000,133432.000000,1.334320e+05,1.334320e+05,129597,132433.0,133423.0,1.334320e+05,1.334320e+05
mean,554947.482493,1.035479,2021-06-30 23:52:25.440374272,2021-07-01 03:21:49.287127552,-17.611715,3.138700e+05,3.126524e+05,14873.793393,0.014913,6.556238e+04,1.806843e+05,2021-06-30 05:39:10.780805376,37.14066,76.667389,2.835391e+12,-3.797744e+15
min,471057.000000,0.000000,2020-12-26 00:00:00,2021-01-02 00:00:00,-8664.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,2020-12-31 15:55:00,1.0,1.0,1.423980e+10,-9.223372e+18
25%,514449.750000,0.000000,2021-04-03 00:00:00,2021-04-03 00:00:00,-44.000000,1.334198e+05,1.329208e+05,15000.000000,0.000000,0.000000e+00,0.000000e+00,2021-04-01 15:44:00,18.0,11.0,2.996711e+12,3.995615e+12
50%,554508.500000,0.000000,2021-07-01 00:00:00,2021-07-02 00:00:00,-22.000000,2.273240e+05,2.265533e+05,15000.000000,0.000000,0.000000e+00,0.000000e+00,2021-06-27 13:56:00,37.0,60.0,2.996730e+12,3.995645e+12
75%,594762.500000,0.000000,2021-09-26 00:00:00,2021-09-26 00:00:00,-5.000000,3.807160e+05,3.795951e+05,15000.000000,0.000000,0.000000e+00,2.487505e+05,2021-09-27 16:39:00,55.0,134.0,2.996923e+12,3.995897e+12
max,638473.000000,5.000000,2021-12-31 00:00:00,2021-12-31 00:00:00,61684.000000,2.818497e+07,1.192000e+07,30000.000000,314.770000,1.516613e+07,1.516613e+07,2021-12-31 15:45:00,98.0,193.0,2.933940e+13,3.995995e+15
std,47199.636471,1.970045,NaN,NaN,363.415501,3.309387e+05,3.209582e+05,5196.972807,1.536663,3.063868e+05,3.520568e+05,NaN,23.1961,63.825378,7.309296e+11,1.872205e+17

## **7**. Подумать и написать, какую дополнительную аналитику можно сделать на основе этих данных, и попытаться реализовать хотя бы одну идею.
---
### 1. Найти топ - 3 филиала с наибольшим количеством заказов с оценкой 5 и отсортировать по убыванию количества таких оценок.

### 2. Рассчитать общую сумму, среднее значение, медиану и максимум для столбца "Всего оплачено с карты". Использовать максимально оптимизированный код для реализации данной логики.
---

In [15]:
# Фильтрация заказов, у которых оценка = 5.
df_raiting_5 = df_excel[df_excel["Оценка заказа"] == 5]

# Группировка по филиалу и подсчет количества оценок 5.
raiting_counts = (
    df_raiting_5
    .groupby("Филиал")["Оценка заказа"]
    .count()
    .reset_index(name="Количество оценок 5")
    )

# Сортировка по убыванию.
raiting_counts_sorted = (
    raiting_counts
    .sort_values(by = "Количество оценок 5", ascending = False)
    )

# Сброс индекса для упрощения отображения и вывод топ 3 филиала
# с наибольшим количеством заказов с оценкой 5.
raiting_counts_sorted.reset_index(drop = True).head(3)

       Филиал  Количество оценок 5
0     Shedevr                 4582
1       Салом                 4287
2  Сарыкулька                 3240

In [16]:
# Указываем список необходимых статистических функций
my_stats = ["sum", "mean", "median", "max"]

# Преобразование последней колонки в целые числа БЕЗ научной нотации:
# .fillna(0) — заменяет NaN на 0
# .round(0) — если есть float с дробной частью, делает округление
# .astype(int) — приводит к int (бросит ошибку, если остаются нецелые значения)
# .to_frame() — преобразует результат в DataFrame
# .T — транспонирует DataFrame, чтобы результат статистики стали строками, а не столбцами
(
    df_excel["Всего оплачено с карты"]
    .agg(my_stats)
    .fillna(0)
    .round(0)
    .astype(int)
    .to_frame().T
    )

                                sum    mean  median       max
Всего оплачено с карты  24109061898  180684       0  15166134

## **8**. Проверить, сколько строк соответствует определенному условию, например: заказы после определенной даты или заказы по конкретному ID клиента
---
### Определить топ-5 клиентов по количеству заказов, выполненных в декабре.
---

In [17]:
# Фильтрация заказов, созданных в декабре
df_december = df_excel[df_excel["Дата создания заказа"].dt.month == 12]

# Подсчет количества сделанных заказов каждым клиентом в декабре
df_december_counts = (
    df_december
    .groupby("Номер клиента")["Номер заказов"]
    .count()
    .reset_index(name = "Количество заказов в декабре")
    )

# Сортировка по количеству заказов в декабре в порядке убывания
df_top5 = (
    df_december_counts
    .sort_values(by = "Количество заказов в декабре", ascending = False)
    ).reset_index(drop = True).head(5)

# Вывод результата
df_top5

   Номер клиента  Количество заказов в декабре
0  2996998765352                            76
1  2996793952037                            47
2  2996728187702                            38
3  2996806998587                            27
4  2996999912408                            21

## **9**. Найти **минимальную** и **максимальную** дату в колонке с датами, отсортировав данные и посмотрев первую и последнюю строку.
---

In [18]:
# Сортируем DataFrame по дате по возрастанию
df_sorted = df_excel.sort_values(by = "Дата создания заказа", ascending = True)

# Получаем минимальную и максимальную дату (первая и последняя строки)
min_order_date = df_sorted.iloc[0]["Дата создания заказа"]
max_order_date = df_sorted.iloc[-1]["Дата создания заказа"]

# Выводим результат
# .strftime("%d-%m-%Y") — форматирует дату в строку в формате "день-месяц-год"
print("Минимальная дата:", min_order_date.strftime("%d-%m-%Y"))
print("Максимальная дата:", max_order_date.strftime("%d-%m-%Y"))

Минимальная дата: 26-12-2020
Максимальная дата: 31-12-2021

## **10**. Посчитать количество уникальных значений в выбранной колонке, например, сколько разных клиентов или адресов доставки.
---
### 1. Количество разных клиентов.

In [19]:
# Получаем уникальные номера клиентов
unique_clients = df_excel["Номер клиента"].unique()

# Количество уникальных клиентов
unique_clients_count = len(unique_clients)

# Выводим количество уникальных клиентов
print("Количество уникальных клиентов:", unique_clients_count)

Количество уникальных клиентов: 16611

### 2. Количество разных адресов доставки.

In [20]:
# Получаем уникальные номера адресов доставки
unique_addresses = df_excel["Номер адреса доставки"].unique()

# Количество уникальных адресов доставки
unique_addresses_count = len(unique_addresses)

# Выводим количество уникальных адресов доставки
print("Количество уникальных адресов доставки:", unique_addresses_count)

Количество уникальных адресов доставки: 17522

## **11**. Отфильтровать заказы для конкретного клиента и изучить только их: сколько заказов, на какие даты.
---
### Найти клиента, который сделал больше всего заказов (топ-1 клиент).

In [21]:
# Группируем таблицу по "Номер клиента", считаем количество заказов для каждого клиента
df_orders_by_client = (
    df_excel
    .groupby("Номер клиента")["Номер заказов"]
    .count()
    .reset_index(name = "Количество заказов") # преобразуем результат в датафрейм и задаём имя новой колонки
    .sort_values(by = "Количество заказов", ascending = False) # сортируем по убыванию количества заказов
)

# Извлекаем ID клиента, который сделал наибольшее количество заказов (первая строка)
top_client_id = df_orders_by_client.iloc[0]["Номер клиента"]

# Фильтруем основной датафрейм: оставляем только заказы выбранного клиента
df_top_client_orders = df_excel[df_excel["Номер клиента"] == top_client_id]

# Получаем все даты заказов клиента и сортируем их по возрастанию
dates_of_orders = df_top_client_orders["Дата создания заказа"].sort_values(ascending = True)

# Выводим ID клиента с наибольшим числом заказов
print(f"ID клиента: {top_client_id}\n")

# Выводим общее количество заказов, сделанных этим клиентом
print(f"Общее количество сделанных заказов: {len(df_top_client_orders)}\n")

# Выводим заголовок для списка дат заказов
print("Даты заказов:")

# Выводим отсортированные даты всех заказов этого клиента
print(dates_of_orders.reset_index(drop = True).to_string(index = False))

ID клиента: 2996136003341

Общее количество сделанных заказов: 1778

Даты заказов:
2020-12-29
2021-01-02
2021-01-02
2021-01-02
2021-01-02
2021-01-02
2021-01-03
2021-01-03
2021-01-03
2021-01-04
2021-01-05
2021-01-05
2021-01-05
2021-01-05
2021-01-05
2021-01-05
2021-01-06
2021-01-06
2021-01-07
2021-01-07
2021-01-07
2021-01-07
2021-01-07
2021-01-07
2021-01-08
2021-01-08
2021-01-08
2021-01-08
2021-01-08
2021-01-08
2021-01-09
2021-01-09
2021-01-09
2021-01-09
2021-01-10
2021-01-10
2021-01-10
2021-01-10
2021-01-10
2021-01-11
2021-01-11
2021-01-11
2021-01-11
2021-01-11
2021-01-11
2021-01-12
2021-01-12
2021-01-12
2021-01-12
2021-01-12
2021-01-12
2021-01-13
2021-01-13
2021-01-13
2021-01-13
2021-01-13
2021-01-13
2021-01-14
2021-01-14
2021-01-14
2021-01-14
2021-01-14
2021-01-15
2021-01-15
2021-01-15
2021-01-15
2021-01-15
2021-01-15
2021-01-16
2021-01-16
2021-01-16
2021-01-16
2021-01-16
2021-01-17
2021-01-17
2021-01-17
2021-01-17
2021-01-17
2021-01-17
2021-01-17
2021-01-17
2021-01-18
2021-01-18
2021-01-18
2021-01-18
2021-01-18
2021-01-18
2021-01-18
2021-01-19
2021-01-19
2021-01-19
2021-01-19
2021-01-19
2021-01-20
2021-01-20
2021-01-20
2021-01-20
2021-01-20
2021-01-20
2021-01-20
2021-01-21
2021-01-21
2021-01-21
2021-01-21
2021-01-21
2021-01-21
2021-01-21
2021-01-21
2021-01-21
2021-01-21
2021-01-21
2021-01-21
2021-01-22
2021-01-22
2021-01-22
2021-01-22
2021-01-22
2021-01-22
2021-01-22
2021-01-22
2021-01-23
2021-01-23
2021-01-23
2021-01-23
2021-01-23
2021-01-23
2021-01-23
2021-01-23
2021-01-24
2021-01-24
2021-01-24
2021-01-24
2021-01-24
2021-01-24
2021-01-25
2021-01-25
2021-01-25
2021-01-25
2021-01-25
2021-01-25
2021-01-25
2021-01-25
2021-01-25
2021-01-25
2021-01-25
2021-01-25
2021-01-26
2021-01-26
2021-01-26
2021-01-26
2021-01-26
2021-01-26
2021-01-26
2021-01-26
2021-01-26
2021-01-26
2021-01-26
2021-01-27
2021-01-27
2021-01-27
2021-01-27
2021-01-28
2021-01-29
2021-01-29
2021-01-29
2021-01-30
2021-01-30
2021-01-30
2021-01-31
2021-01-31
2021-01-31
2021-02-01
2021-02-01
2021-02-01
2021-02-02
2021-02-02
2021-02-02
2021-02-03
2021-02-03
2021-02-03
2021-02-03
2021-02-03
2021-02-04
2021-02-04
2021-02-04
2021-02-04
2021-02-04
2021-02-04
2021-02-04
2021-02-04
2021-02-04
2021-02-04
2021-02-04
2021-02-05
2021-02-05
2021-02-05
2021-02-05
2021-02-05
2021-02-05
2021-02-05
2021-02-05
2021-02-06
2021-02-06
2021-02-06
2021-02-06
2021-02-06
2021-02-06
2021-02-06
2021-02-07
2021-02-07
2021-02-08
2021-02-08
2021-02-08
2021-02-08
2021-02-09
2021-02-09
2021-02-09
2021-02-09
2021-02-09
2021-02-09
2021-02-10
2021-02-10
2021-02-10
2021-02-10
2021-02-11
2021-02-11
2021-02-11
2021-02-11
2021-02-12
2021-02-12
2021-02-12
2021-02-12
2021-02-12
2021-02-12
2021-02-13
2021-02-13
2021-02-13
2021-02-13
2021-02-13
2021-02-13
2021-02-13
2021-02-13
2021-02-13
2021-02-13
2021-02-14
2021-02-14
2021-02-14
2021-02-14
2021-02-14
2021-02-14
2021-02-14
2021-02-14
2021-02-15
2021-02-15
2021-02-15
2021-02-15
2021-02-16
2021-02-16
2021-02-16
2021-02-16
2021-02-16
2021-02-16
2021-02-16
2021-02-16
2021-02-16
2021-02-16
2021-02-17
2021-02-17
2021-02-17
2021-02-17
2021-02-17
2021-02-17
2021-02-18
2021-02-18
2021-02-18
2021-02-18
2021-02-18
2021-02-18
2021-02-19
2021-02-19
2021-02-19
2021-02-19
2021-02-19
2021-02-19
2021-02-19
2021-02-19
2021-02-19
2021-02-19
2021-02-20
2021-02-20
2021-02-20
2021-02-20
2021-02-21
2021-02-21
2021-02-21
2021-02-21
2021-02-21
2021-02-22
2021-02-22
2021-02-22
2021-02-23
2021-02-23
2021-02-23
2021-02-23
2021-02-23
2021-02-23
2021-02-23
2021-02-23
2021-02-23
2021-02-23
2021-02-23
2021-02-23
2021-02-24
2021-02-24
2021-02-24
2021-02-24
2021-02-24
2021-02-24
2021-02-24
2021-02-24
2021-02-24
2021-02-24
2021-02-25
2021-02-25
2021-02-26
2021-02-26
2021-02-26
2021-02-26
2021-02-26
2021-02-26
2021-02-26
2021-02-26
2021-02-26
2021-02-27
2021-02-27
2021-02-27
2021-02-27
2021-02-28
2021-02-28
2021-02-28
2021-02-28
2021-02-28
2021-02-28
2021-02-28
2021-02-28
2021-03-01
2021-03-01
2021-03-01
2021-03-02
2021-03-02
2021-03-02
2021-03-03
2021-03-03
2021-03-03
2021-03-03
2021-03-03
2021-03-03
2021-03-03
2021-03-03
2021-03-03
2021-03-04
2021-03-04
2021-03-04
2021-03-04
2021-03-04
2021-03-04
2021-03-04
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-05
2021-03-06
2021-03-06
2021-03-06
2021-03-06
2021-03-06
2021-03-06
2021-03-06
2021-03-06
2021-03-06
2021-03-06
2021-03-06
2021-03-07
2021-03-07
2021-03-07
2021-03-07
2021-03-07
2021-03-07
2021-03-07
2021-03-07
2021-03-07
2021-03-08
2021-03-08
2021-03-08
2021-03-09
2021-03-09
2021-03-09
2021-03-09
2021-03-09
2021-03-10
2021-03-10
2021-03-10
2021-03-11
2021-03-11
2021-03-11
2021-03-11
2021-03-12
2021-03-12
2021-03-12
2021-03-12
2021-03-12
2021-03-12
2021-03-12
2021-03-12
2021-03-12
2021-03-12
2021-03-13
2021-03-13
2021-03-13
2021-03-13
2021-03-13
2021-03-13
2021-03-14
2021-03-14
2021-03-14
2021-03-14
2021-03-14
2021-03-14
2021-03-14
2021-03-14
2021-03-15
2021-03-15
2021-03-15
2021-03-15
2021-03-16
2021-03-16
2021-03-16
2021-03-16
2021-03-16
2021-03-16
2021-03-16
2021-03-16
2021-03-16
2021-03-16
2021-03-17
2021-03-17
2021-03-17
2021-03-17
2021-03-17
2021-03-17
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-18
2021-03-19
2021-03-19
2021-03-19
2021-03-19
2021-03-19
2021-03-19
2021-03-19
2021-03-19
2021-03-20
2021-03-20
2021-03-21
2021-03-21
2021-03-21
2021-03-22
2021-03-22
2021-03-22
2021-03-22
2021-03-22
2021-03-22
2021-03-22
2021-03-22
2021-03-22
2021-03-22
2021-03-22
2021-03-23
2021-03-23
2021-03-23
2021-03-23
2021-03-23
2021-03-23
2021-03-23
2021-03-23
2021-03-23
2021-03-23
2021-03-24
2021-03-24
2021-03-24
2021-03-24
2021-03-24
2021-03-24
2021-03-25
2021-03-25
2021-03-25
2021-03-25
2021-03-25
2021-03-25
2021-03-25
2021-03-25
2021-03-26
2021-03-26
2021-03-26
2021-03-26
2021-03-26
2021-03-27
2021-03-28
2021-03-29
2021-03-29
2021-03-29
2021-03-29
2021-03-29
2021-03-29
2021-03-30
2021-03-30
2021-03-30
2021-03-30
2021-03-30
2021-03-30
2021-03-30
2021-03-30
2021-03-30
2021-03-30
2021-03-30
2021-03-31
2021-03-31
2021-03-31
2021-03-31
2021-04-01
2021-04-01
2021-04-01
2021-04-01
2021-04-01
2021-04-02
2021-04-02
2021-04-02
2021-04-02
2021-04-02
2021-04-02
2021-04-02
2021-04-02
2021-04-02
2021-04-02
2021-04-03
2021-04-03
2021-04-03
2021-04-03
2021-04-03
2021-04-04
2021-04-04
2021-04-04
2021-04-04
2021-04-04
2021-04-05
2021-04-05
2021-04-05
2021-04-05
2021-04-05
2021-04-05
2021-04-05
2021-04-05
2021-04-05
2021-04-06
2021-04-06
2021-04-06
2021-04-06
2021-04-06
2021-04-06
2021-04-06
2021-04-06
2021-04-06
2021-04-07
2021-04-07
2021-04-07
2021-04-07
2021-04-07
2021-04-07
2021-04-07
2021-04-07
2021-04-08
2021-04-08
2021-04-08
2021-04-08
2021-04-08
2021-04-08
2021-04-08
2021-04-09
2021-04-09
2021-04-09
2021-04-09
2021-04-09
2021-04-09
2021-04-09
2021-04-09
2021-04-09
2021-04-09
2021-04-09
2021-04-10
2021-04-10
2021-04-10
2021-04-10
2021-04-10
2021-04-10
2021-04-10
2021-04-11
2021-04-11
2021-04-11
2021-04-12
2021-04-12
2021-04-12
2021-04-12
2021-04-12
2021-04-13
2021-04-13
2021-04-13
2021-04-13
2021-04-13
2021-04-14
2021-04-14
2021-04-14
2021-04-14
2021-04-14
2021-04-14
2021-04-14
2021-04-14
2021-04-15
2021-04-15
2021-04-15
2021-04-15
2021-04-15
2021-04-15
2021-04-15
2021-04-15
2021-04-15
2021-04-15
2021-04-15
2021-04-16
2021-04-16
2021-04-16
2021-04-16
2021-04-16
2021-04-16
2021-04-16
2021-04-16
2021-04-17
2021-04-17
2021-04-17
2021-04-17
2021-04-18
2021-04-18
2021-04-18
2021-04-18
2021-04-18
2021-04-18
2021-04-18
2021-04-19
2021-04-19
2021-04-19
2021-04-19
2021-04-19
2021-04-19
2021-04-19
2021-04-20
2021-04-20
2021-04-20
2021-04-20
2021-04-20
2021-04-20
2021-04-20
2021-04-21
2021-04-22
2021-04-22
2021-04-22
2021-04-22
2021-04-22
2021-04-22
2021-04-23
2021-04-23
2021-04-23
2021-04-23
2021-04-23
2021-04-23
2021-04-23
2021-04-24
2021-04-24
2021-04-24
2021-04-24
2021-04-25
2021-04-25
2021-04-25
2021-04-25
2021-04-25
2021-04-25
2021-04-25
2021-04-26
2021-04-26
2021-04-26
2021-04-26
2021-04-26
2021-04-26
2021-04-26
2021-04-27
2021-04-27
2021-04-27
2021-04-28
2021-04-28
2021-04-28
2021-04-28
2021-04-28
2021-04-28
2021-04-28
2021-04-28
2021-04-28
2021-04-28
2021-04-28
2021-04-28
2021-04-29
2021-04-29
2021-04-29
2021-04-29
2021-04-29
2021-04-29
2021-04-29
2021-04-29
2021-04-29
2021-04-29
2021-04-30
2021-04-30
2021-04-30
2021-04-30
2021-04-30
2021-04-30
2021-04-30
2021-04-30
2021-04-30
2021-05-01
2021-05-01
2021-05-01
2021-05-01
2021-05-02
2021-05-02
2021-05-02
2021-05-02
2021-05-03
2021-05-03
2021-05-03
2021-05-04
2021-05-04
2021-05-04
2021-05-04
2021-05-05
2021-05-05
2021-05-05
2021-05-05
2021-05-05
2021-05-05
2021-05-05
2021-05-06
2021-05-06
2021-05-06
2021-05-06
2021-05-07
2021-05-07
2021-05-07
2021-05-07
2021-05-08
2021-05-08
2021-05-08
2021-05-08
2021-05-08
2021-05-08
2021-05-09
2021-05-09
2021-05-10
2021-05-10
2021-05-10
2021-05-10
2021-05-10
2021-05-11
2021-05-11
2021-05-11
2021-05-11
2021-05-11
2021-05-11
2021-05-11
2021-05-12
2021-05-12
2021-05-12
2021-05-12
2021-05-12
2021-05-12
2021-05-12
2021-05-12
2021-05-12
2021-05-12
2021-05-12
2021-05-12
2021-05-13
2021-05-13
2021-05-13
2021-05-13
2021-05-14
2021-05-14
2021-05-14
2021-05-14
2021-05-14
2021-05-14
2021-05-14
2021-05-15
2021-05-16
2021-05-16
2021-05-16
2021-05-16
2021-05-17
2021-05-17
2021-05-18
2021-05-18
2021-05-18
2021-05-18
2021-05-18
2021-05-18
2021-05-18
2021-05-19
2021-05-19
2021-05-19
2021-05-19
2021-05-19
2021-05-19
2021-05-19
2021-05-19
2021-05-19
2021-05-20
2021-05-20
2021-05-20
2021-05-20
2021-05-20
2021-05-20
2021-05-20
2021-05-20
2021-05-20
2021-05-20
2021-05-21
2021-05-21
2021-05-21
2021-05-21
2021-05-21
2021-05-21
2021-05-21
2021-05-21
2021-05-22
2021-05-23
2021-05-23
2021-05-23
2021-05-23
2021-05-23
2021-05-23
2021-05-23
2021-05-23
2021-05-24
2021-05-24
2021-05-24
2021-05-24
2021-05-24
2021-05-25
2021-05-25
2021-05-25
2021-05-25
2021-05-25
2021-05-25
2021-05-25
2021-05-25
2021-05-25
2021-05-25
2021-05-25
2021-05-25
2021-05-26
2021-05-26
2021-05-26
2021-05-26
2021-05-26
2021-05-26
2021-05-26
2021-05-27
2021-05-27
2021-05-27
2021-05-27
2021-05-27
2021-05-27
2021-05-28
2021-05-28
2021-05-28
2021-05-28
2021-05-28
2021-05-28
2021-05-28
2021-05-29
2021-05-29
2021-05-30
2021-05-30
2021-05-30
2021-05-30
2021-05-30
2021-05-30
2021-05-30
2021-05-31
2021-05-31
2021-05-31
2021-05-31
2021-05-31
2021-05-31
2021-05-31
2021-06-01
2021-06-01
2021-06-01
2021-06-01
2021-06-02
2021-06-02
2021-06-02
2021-06-02
2021-06-02
2021-06-02
2021-06-03
2021-06-03
2021-06-03
2021-06-03
2021-06-03
2021-06-03
2021-06-04
2021-06-04
2021-06-04
2021-06-04
2021-06-05
2021-06-06
2021-06-06
2021-06-06
2021-06-06
2021-06-06
2021-06-06
2021-06-06
2021-06-06
2021-06-06
2021-06-06
2021-06-07
2021-06-07
2021-06-07
2021-06-07
2021-06-08
2021-06-08
2021-06-08
2021-06-08
2021-06-08
2021-06-08
2021-06-09
2021-06-09
2021-06-09
2021-06-09
2021-06-09
2021-06-09
2021-06-09
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-10
2021-06-11
2021-06-11
2021-06-11
2021-06-11
2021-06-11
2021-06-11
2021-06-11
2021-06-11
2021-06-11
2021-06-12
2021-06-12
2021-06-12
2021-06-12
2021-06-12
2021-06-12
2021-06-12
2021-06-12
2021-06-13
2021-06-13
2021-06-14
2021-06-14
2021-06-15
2021-06-15
2021-06-15
2021-06-15
2021-06-15
2021-06-15
2021-06-15
2021-06-15
2021-06-16
2021-06-16
2021-06-16
2021-06-16
2021-06-16
2021-06-17
2021-06-17
2021-06-17
2021-06-17
2021-06-18
2021-06-18
2021-06-18
2021-06-18
2021-06-18
2021-06-18
2021-06-18
2021-06-18
2021-06-18
2021-06-19
2021-06-19
2021-06-19
2021-06-19
2021-06-19
2021-06-19
2021-06-19
2021-06-20
2021-06-20
2021-06-20
2021-06-20
2021-06-21
2021-06-21
2021-06-21
2021-06-21
2021-06-21
2021-06-21
2021-06-21
2021-06-21
2021-06-21
2021-06-22
2021-06-22
2021-06-22
2021-06-22
2021-06-22
2021-06-22
2021-06-22
2021-06-22
2021-06-22
2021-06-22
2021-06-23
2021-06-23
2021-06-24
2021-06-24
2021-06-24
2021-06-24
2021-06-24
2021-06-24
2021-06-24
2021-06-24
2021-06-24
2021-06-24
2021-06-24
2021-06-24
2021-06-25
2021-06-25
2021-06-25
2021-06-25
2021-06-25
2021-06-26
2021-06-26
2021-06-27
2021-06-28
2021-06-28
2021-06-28
2021-06-28
2021-06-28
2021-06-28
2021-06-28
2021-06-29
2021-06-29
2021-06-29
2021-06-29
2021-06-29
2021-06-29
2021-06-29
2021-06-29
2021-06-29
2021-06-29
2021-06-30
2021-06-30
2021-06-30
2021-06-30
2021-06-30
2021-06-30
2021-06-30
2021-06-30
2021-06-30
2021-06-30
2021-07-01
2021-07-01
2021-07-01
2021-07-01
2021-07-01
2021-07-01
2021-07-01
2021-07-02
2021-07-02
2021-07-02
2021-07-02
2021-07-02
2021-07-02
2021-07-03
2021-07-03
2021-07-03
2021-07-04
2021-07-04
2021-07-04
2021-07-04
2021-07-04
2021-07-05
2021-07-05
2021-07-05
2021-07-05
2021-07-05
2021-07-05
2021-07-05
2021-07-05
2021-07-05
2021-07-05
2021-07-05
2021-07-06
2021-07-06
2021-07-06
2021-07-06
2021-07-06
2021-07-06
2021-07-06
2021-07-06
2021-07-06
2021-07-07
2021-07-07
2021-07-07
2021-07-07
2021-07-07
2021-07-08
2021-07-08
2021-07-08
2021-07-08
2021-07-08
2021-07-08
2021-07-08
2021-07-08
2021-07-08
2021-07-08
2021-07-08
2021-07-08
2021-07-09
2021-07-09
2021-07-09
2021-07-09
2021-07-09
2021-07-10
2021-07-10
2021-07-10
2021-07-10
2021-07-10
2021-07-10
2021-07-10
2021-07-10
2021-07-10
2021-07-10
2021-07-10
2021-07-11
2021-07-11
2021-07-11
2021-07-11
2021-07-11
2021-07-12
2021-07-12
2021-07-12
2021-07-12
2021-07-12
2021-07-12
2021-07-12
2021-07-12
2021-07-12
2021-07-13
2021-07-13
2021-07-13
2021-07-13
2021-07-13
2021-07-13
2021-07-13
2021-07-13
2021-07-13
2021-07-13
2021-07-13
2021-07-13
2021-07-14
2021-07-14
2021-07-14
2021-07-14
2021-07-14
2021-07-14
2021-07-14
2021-07-14
2021-07-14
2021-07-14
2021-07-14
2021-07-15
2021-07-15
2021-07-15
2021-07-15
2021-07-15
2021-07-15
2021-07-15
2021-07-16
2021-07-16
2021-07-16
2021-07-16
2021-07-16
2021-07-16
2021-07-16
2021-07-16
2021-07-16
2021-07-16
2021-07-16
2021-07-17
2021-07-17
2021-07-17
2021-07-17
2021-07-17
2021-07-17
2021-07-18
2021-07-18
2021-07-18
2021-07-18
2021-07-18
2021-07-18
2021-07-18
2021-07-18
2021-07-19
2021-07-19
2021-07-19
2021-07-19
2021-07-19
2021-07-19
2021-07-19
2021-07-19
2021-07-19
2021-07-19
2021-07-19
2021-07-19
2021-07-20
2021-07-20
2021-07-20
2021-07-20
2021-07-20
2021-07-21
2021-07-21
2021-07-21
2021-07-21
2021-07-21
2021-07-21
2021-07-21
2021-07-21
2021-07-22
2021-07-22
2021-07-22
2021-07-22
2021-07-22
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-23
2021-07-24
2021-07-24
2021-07-24
2021-07-24
2021-07-24
2021-07-24
2021-07-24
2021-07-24
2021-07-25
2021-07-25
2021-07-26
2021-07-26
2021-07-26
2021-07-26
2021-07-26
2021-07-26
2021-07-26
2021-07-26
2021-07-27
2021-07-27
2021-07-27
2021-07-27
2021-07-27
2021-07-27
2021-07-27
2021-07-28
2021-07-28
2021-07-28
2021-07-28
2021-07-28
2021-07-28
2021-07-28
2021-07-28
2021-07-28
2021-07-29
2021-07-29
2021-07-29
2021-07-29
2021-07-29
2021-07-29
2021-07-29
2021-07-29
2021-07-30
2021-07-30
2021-07-30
2021-07-30
2021-07-30
2021-07-30
2021-07-30
2021-07-30
2021-07-30
2021-07-30
2021-07-30
2021-07-31
2021-07-31
2021-07-31
2021-07-31
2021-08-01
2021-08-01
2021-08-01
2021-08-01
2021-08-02
2021-08-02
2021-08-02
2021-08-02
2021-08-02
2021-08-02
2021-08-02
2021-08-03
2021-08-03
2021-08-03
2021-08-03
2021-08-03
2021-08-03
2021-08-03
2021-08-04
2021-08-04
2021-08-04
2021-08-05
2021-08-05
2021-08-05
2021-08-05
2021-08-05
2021-08-05
2021-08-06
2021-08-06
2021-08-06
2021-08-06
2021-08-06
2021-08-06
2021-08-07
2021-08-07
2021-08-07
2021-08-07
2021-08-08
2021-08-08
2021-08-08
2021-08-08
2021-08-09
2021-08-09
2021-08-09
2021-08-09
2021-08-09
2021-08-09
2021-08-10
2021-08-10
2021-08-10
2021-08-10
2021-08-10
2021-08-10
2021-08-10
2021-08-11
2021-08-11
2021-08-11
2021-08-11
2021-08-11
2021-08-11
2021-08-12
2021-08-12
2021-08-12
2021-08-12
2021-08-12
2021-08-12
2021-08-12
2021-08-12
2021-08-12
2021-08-12
2021-08-12
2021-08-13
2021-08-13
2021-08-13
2021-08-13
2021-08-13
2021-08-14
2021-08-14
2021-08-14
2021-08-15
2021-08-15
2021-08-15
2021-08-16
2021-08-16
2021-08-16
2021-08-16
2021-08-16
2021-08-16
2021-08-16
2021-08-16
2021-08-16
2021-08-17
2021-08-17
2021-08-17
2021-08-18
2021-08-18
2021-08-18
2021-08-18
2021-08-19
2021-08-20
2021-08-20
2021-08-20
2021-08-20
2021-08-21
2021-08-21
2021-08-21
2021-08-21
2021-08-22
2021-08-22
2021-08-23
2021-08-23
2021-08-23
2021-08-23
2021-08-23
2021-08-23
2021-08-24
2021-08-24
2021-08-24
2021-08-24
2021-08-25
2021-08-25
2021-08-25
2021-08-25
2021-08-25
2021-08-25
2021-08-26
2021-08-26
2021-08-26
2021-08-26
2021-08-26
2021-08-26
2021-08-26
2021-08-27
2021-08-27
2021-08-27
2021-08-27
2021-08-27
2021-08-27
2021-08-27
2021-08-28
2021-08-28
2021-08-28
2021-08-28
2021-08-28
2021-08-28
2021-08-28
2021-08-28
2021-08-28
2021-08-28
2021-08-28
2021-08-28
2021-08-29
2021-08-29
2021-08-29
2021-08-30
2021-08-30
2021-08-31
2021-08-31
2021-08-31
2021-08-31
2021-08-31
2021-08-31
2021-08-31
2021-08-31
2021-08-31
2021-09-01
2021-09-01
2021-09-01
2021-09-01
2021-09-01
2021-09-01
2021-09-02
2021-09-02
2021-09-03
2021-09-03
2021-09-03
2021-09-03
2021-09-03
2021-09-03
2021-09-03
2021-09-03
2021-09-03
2021-09-04
2021-09-04
2021-09-04
2021-09-04
2021-09-04
2021-09-04
2021-09-04
2021-09-05
2021-09-06
2021-09-06
2021-09-06
2021-09-06
2021-09-07
2021-09-07
2021-09-07
2021-09-07
2021-09-07
2021-09-07
2021-09-07
2021-09-07
2021-09-08
2021-09-08
2021-09-08
2021-09-08
2021-09-08
2021-09-08
2021-09-08
2021-09-08
2021-09-08
2021-09-08
2021-09-08
2021-09-09
2021-09-09
2021-09-09
2021-09-09
2021-09-09
2021-09-09
2021-09-10
2021-09-10
2021-09-10
2021-09-10
2021-09-10
2021-09-10
2021-09-10
2021-09-10
2021-09-10
2021-09-10
2021-09-10
2021-09-11
2021-09-11
2021-09-11
2021-09-11
2021-09-12
2021-09-12
2021-09-12
2021-09-12
2021-09-12
2021-09-12
2021-09-12
2021-09-12
2021-09-12
2021-09-13
2021-09-13
2021-09-13
2021-09-13
2021-09-13
2021-09-13
2021-09-13
2021-09-13
2021-09-14
2021-09-14
2021-09-14
2021-09-15
2021-09-15
2021-09-15
2021-09-15
2021-09-15
2021-09-15
2021-09-16
2021-09-16
2021-09-16
2021-09-17
2021-09-17
2021-09-18
2021-09-18
2021-09-18
2021-09-18
2021-09-18
2021-09-18
2021-09-18
2021-09-18
2021-09-18
2021-09-18
2021-09-19
2021-09-19
2021-09-19
2021-09-19
2021-09-19
2021-09-20
2021-09-20
2021-09-20
2021-09-20
2021-09-21
2021-09-21
2021-09-21
2021-09-21
2021-09-22
2021-09-22
2021-09-22
2021-09-23
2021-09-23
2021-09-23
2021-09-23
2021-09-23
2021-09-23
2021-09-24
2021-09-24
2021-09-24
2021-09-24
2021-09-24
2021-09-24
2021-09-25
2021-09-25
2021-09-25
2021-09-25
2021-09-25
2021-09-25
2021-09-25
2021-09-25
2021-09-25
2021-09-25
2021-09-25
2021-09-25
2021-09-26
2021-09-26
2021-09-26
2021-09-26
2021-09-26
2021-09-26
2021-09-27
2021-09-27
2021-09-28
2021-09-28
2021-09-28
2021-09-28
2021-09-28
2021-09-28
2021-09-29
2021-09-29
2021-09-29
2021-09-29
2021-09-29
2021-09-29
2021-09-29
2021-09-29
2021-09-29
2021-09-29
2021-09-29
2021-09-30
2021-09-30
2021-09-30
2021-09-30
2021-10-01
2021-10-01
2021-10-01
2021-10-01
2021-10-02
2021-10-02
2021-10-03
2021-10-04
2021-10-04
2021-10-04
2021-10-05
2021-10-05
2021-10-05
2021-10-05
2021-10-05
2021-10-05
2021-10-05
2021-10-06
2021-10-06
2021-10-06
2021-10-06
2021-10-06
2021-10-06
2021-10-06
2021-10-07
2021-10-07
2021-10-07
2021-10-07
2021-10-07
2021-10-07
2021-10-07
2021-10-08
2021-10-08
2021-10-08
2021-10-08
2021-10-08
2021-10-08
2021-10-09
2021-10-09
2021-10-09
2021-10-10
2021-10-10
2021-10-10
2021-10-10
2021-10-11
2021-10-11
2021-10-11
2021-10-11
2021-10-11
2021-10-11
2021-10-11
2021-10-11
2021-10-11
2021-10-12
2021-10-12
2021-10-12
2021-10-12
2021-10-12
2021-10-12
2021-10-12
2021-10-13
2021-10-13
2021-10-14
2021-10-14
2021-10-14
2021-10-14
2021-10-14
2021-10-14
2021-10-30

## **12**. Написать список всех функций которые рассматривались на уроке и описать что каждая из них делает в 1-2 предложениях.
---
### **1**. `pd.DataFrame()` - создаёт таблицу (двумерную структуру данных). Применяется для создания и работы с таблицами (похож на Excel-таблицу).
---
### **2**. `pd.Series()` - создаёт одномерную структуру данных, похожую на столбец из таблицы или на список.
---
### **3**. `pd.read_excel()` - считывает данные из файла Excel (формата .xlsx, .xls) и загружает в таблицу.
---
### **4**. `pd.read_csv()` - считывает данные из файла CSV (формата .csv) и загружает в таблицу.
---
### **5**. `DataFrame.head() / Series.head()` - возвращает первые N строк из DataFrame или Series. По умолчанию n = 5. Используется для быстрого просмотра верхней части данных.
---
### **6**. `DataFrame.tail() / Series.tail()` - возвращает последние N строк из DataFrame или Series. По умолчанию n = 5. Используется для быстрого просмотра нижней части данных.
---
### **7**. `DataFrame.describe()` - используется для получения сводной статистики по DataFrame. Он автоматически рассчитывает количество ненулевых значений (count), среднее значение (mean), стандартное отклонение (std / разброс данных), минимальное значение (min), 25-й, 50-й (медиана) и 75-й процентили (quartiles), а также максимальное значение (max) для каждого числового столбца в DataFrame.
---
### **8**. `DataFrame.info()` - функция `info()` показывает информацию о DataFrame. Включая типы данных и использование памяти memory_usage = "deep" позволяет получить более точную информацию о потреблении памяти. Важно отметить, что использование memory_usage = "deep" может занять больше времени, так как оно требует дополнительного анализа.
---
### **9**. `DataFrame.rename() / Series.rename()` - используется для переименования столбцов или индексов в DataFrame и Series.
---
### **10**. `DataFrame.astype()` - изменяет тип данных столбца.
---
### **11**. `DataFrame.fillna()` - зполняет пропущенные значения (NaN) определённым значением.
---
### **12**. `pd.to_datetime()` - преобразует строку или столбец в формат даты/времени datetime64.
---
### **13**. `DataFrame.groupby()` - группирует данные по значению столбца (как GROUP BY в SQL). Схлопывает данные.
---
### **14**. `DataFrame.count()` - возвращает кол-во непустых (не NaN) значений по столбцам или строкам.
---
### **15**. `DataFrame.reset_index()` - сброс индекса в DataFrame, полезно после groupby().
---
### **16**. `DataFrame.loc[]` - метод `loc` в Pandas используется для **выборки данных** на основе меток (названий) строк и столбцов.
---
### **17**. `DataFrame.iloc[]` - метод `iloc` используется для выборки данных на основе позиций (номеров) строк и столбцов.
---
### **18**. `DataFrame['col'].unique()` - возвращает уникальные значения в столбце.
---
### **19**. `len(df)` - возвращает количество строк (как COUNT(*) в SQL).
---
### **20**. `DataFrame.agg()` - позволяет выполнять несколько агрегатных функций сразу.
---
### **21**. `DataFrame.merge(..., how='inner/left/right/outer')` - Объединяет два DataFrame по ключу, как JOIN в SQL. inner — только совпадающие строки, left — все строки из левого + совпадающие, right — из правого, outer — всё (аналог FULL JOIN).
---
### **22**. `DataFrame.pivot_table()` - Создаёт сводную таблицу похожую в Excel, поддерживает агрегатные функции (sum, mean и др.).
---
### **23**. `DataFrame.pivot()` - создаёт таблицу, где значения становятся строками и столбцами (без агрегации).
---
### **24**. `np.random.randint()` - генерирует случайные целые числа в заданном диапазоне.
---
### **25**. `DataFrame.sample() / Series.sample()` - используется для случайной выборки строк или элементов из DataFrame или Series.
---